name: CI

# Events that trigger workflow
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  windows:
    name: Build (Windows)
    runs-on: windows-2019
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Export Repo URL
        run: echo "REPO_URL=https://github.com/${{ github.repository }}" >> $GITHUB_ENV
      - name: Export Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Clone Submodules
        run: git submodule update --init
      - name: Build Distribution
        shell: pwsh
        run: |
          yarn
          yarn build-native
      - name: Upload App
        uses: actions/upload-artifact@v3
        with:
          name: win-app
          path: ./build
